name: Python CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        python-version: [3.8]
        toxenv: ["django32", "django40"]
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox
          pip install pyquery
          pip install coverage
      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
